spring.datasource.url=jdbc:postgresql://localhost:5432/promptguard_db
spring.datasource.username=user0
spring.datasource.password=user123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
